version: "3.8"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8011:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8012:8080"
    volumes:
      - ./api/urstudx_api.yml:/urstudx_api.yml
    environment:
      SWAGGER_JSON: /urstudx_api.yml
  swagger-api:
    image: stoplight/prism:3
    ports:
      - "4012:4010"
    command: mock -h 0.0.0.0 /urstudx_api.yml
    volumes:
      - ./api/urstudx_api.yml:/urstudx_api.yml
