version: "3.8"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8011:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8012:8080"
    volumes:
      - ./api/openapi/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
  swagger-api:
    image: stoplight/prism:3
    ports:
      - "4012:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./api/openapi/openapi.yaml:/openapi.yaml
