openapi: 3.0.3
info:
  version: 1.0.0
  title: MyTODO OpenAPI
  description: MyTODO OpenAPI Document
servers:
  - url: http://localhost:4012
    description: Mock Server
  - url: http://localhost:3010
    description: localhost
tags:
- name: user
  description: ユーザー
- name: todo
  description: ToDo
paths:
  /v1/users/sign_up:
    $ref: ./paths/users/sign_up.yml
  /v1/users/me:
    $ref: ./paths/users/me.yml
  /v1/todos:
    $ref: ./paths/todos/list.yml
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Credentials or access token for API
  schemas:
    NotAuthorizedError:
      description: 認証不可エラー
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: JWT認証などの認証エラー
          example: Not authorized.
    NotFoundError:
      description: 存在しませんエラー
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: GETしたい情報が見つからないエラー
          example: Your requested Item is not found
